image: microsoft/dotnet:latest

stages: [build, pack]

build:
    stage: build
    script:
         - "echo starting"

pack:
    stage: pack
    only:
        refs:
            - master
    script: 
        - "dotne pack -c Release"
        - "dotnet nuget push -s https://nuget.tebyan.net/nuget src/Extensions/bin/Release/*.nupkg"
        - "dotnet nuget push -s https://nuget.tebyan.net/nuget src/Extensions.Sliding/bin/Release/*.nupkg"
        - "dotnet nuget push -s https://nuget.tebyan.net/nuget src/Extensions.GraphicUtils/bin/Release/*.nupkg"